name: CI/CD Pipeline - Online Podcast Manager

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # CI - Build and Test
  build:
    name: CI - Build and Test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          chmod +x node_modules/.bin/react-scripts

      - name: Build frontend
        run: |
          cd frontend
          CI=false npm run build

  # CD - Deploy to EC2
  deploy:
    name: CD - Deploy to EC2
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      - name: Build frontend
        run: |
          cd frontend
          CI=false yarn run build

      - name: Copy build to web folder
        run: |
          sudo cp -r /home/ubuntu/actions-runner/_work/sampleapp_IFQ636/sampleapp_IFQ636/frontend/build/* /var/www/html/

      - name: Restart backend
        run: |
          pm2 restart backend || pm2 start /home/ubuntu/sampleapp_IFQ636/backend/server.js --name backend
          pm2 save

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx